### ISSUE TITLE
CSync question

### ISSUE THREAD

**Issue by CoolLKKPS** [Inoyuuuuu/GiantExtensionLaddersV2#1]
> idk what happen bc i cannot use discord, but now i can't create any issues in CSync repository, i got no idea, but must something happen, otherwise there's no way can be like that, in my opinion this community is very simple and this is better than other community, so if this can possible break the community, i hope don't happen at this moment

so my question is, can both CSync are installed in my modpack with no conflict? just don't want to update the modpack again at this time, too often that i can't handle

**Comment by CoolLKKPS** [comment]
it looks good actually, but im not completely sure, so i have to confirm this

**Comment by Inoyuuuuu** [comment]
Good question.. Didn't thought of that before updating. :L 
I think no, but I'm not 100% sure. If you do experience problems, you can install Version 2.0.0 of my mod, which uses version 3.1.1 of Sigurd's CSync fork (the big ladder in 2.0.0 is sometimes broken tho).
Will do some tests on this tomorrow. If you can use discord, I'd recommend asking the owner of CSync directly, he made a discord server: https://discord.gg/CMyTmUMP2P (this link is the same one as the one on his github page: https://github.com/Owen3H/CSync).

I hope thunderstore removes their clone of Csync eventually, so this does not become a problem. :[

**Comment by CoolLKKPS** [comment]
hmm it did tell me config sync finished, but yea this issue is a bit annoying

**Comment by CoolLKKPS** [comment]
![image](https://github.com/Inoyuuuuu/GiantExtensionLaddersV2/assets/96377775/0cdc9b33-3761-4ec1-bb5e-29cdb29c34c1)
it should be fine, for now, feel free to close this issue if u also think that's fine, hope in the future we can have more author to solve more potential conflict issues

**Comment by Inoyuuuuu** [comment]
Did some tests myself too and came same conclusion (tested with facility meltdown 2.4.7 [Sigurd-CSync 3.1.1] and GiantExtensionLadders 2.1.0 [Owen-CSync 2.2.2]). As you said, config syncing worked and **it should be fine** (although it is annoying to have 2 CSyncs). 
Thanks for submitting your question tho (and even answering it yourself lol)!
Hope you have fun with the mods don't run into problems! <3
