### ISSUE TITLE
A question about CSync

### ISSUE THREAD

**Issue by Kablumbaa** [Inoyuuuuu/GiantExtensionLaddersV2#3]
Is there any chance for this mod to use the Sigurds CSync instead of the Owen3H? I have tried using the Sigurds CSync but the mod doesn't work. Great mod by the way, thanks!

**Comment by Inoyuuuuu** [comment]
Hey, I'm glad you like my mod. c:

I'm sorry for the confusion the two CSyncs caused, I already asked Thunderstore to remove their version, but they won't...
**I probably won't switch, the two CSyncs work fine alongside each other** (if not, please let me know, or inform [Owen](https://github.com/Owen3H), the creator of CSync). I know it seems weird, but you can simply put both in one modpack!

The reason for my decision is that Owen's CSync is the original and continues to be supported by its creator. Owen left Thunderstore (he had his reasons), so they forked his CSync and did Sigurd's CSync. Owen eventually came back, but now there are two CSyncs on Thunderstore...

Hope this helps!

**Comment by Kablumbaa** [comment]
Ah i see, thanks for the quick answer i really appreciate it. I was worried that the both versions of CSync being present might cause problems.
